### ISSUE TITLE
Custom template files

### ISSUE THREAD

**Issue by lime** [damian/js-routes-rails#1]
Hi, and thanks for a really useful little gem! I'm in the process of moving a codebase from `js-routes` to `js-routes-rails`, and it's been smooth sailing so far.

I have one feature suggestion that I'd also be happy to implement: custom templates.

## What?

I should be able to pass an absolute path as the `template` option, e.g:

```rb
routes_dir = Rails.root.join('app', 'assets', 'javascripts', 'routes')

Js::Routes::Rails.configure do |c|
  c.output = File.join(routes_dir, 'index.js')
  c.template = File.join(routes_dir, 'template.js.erb')
end
```

## Why?

While the included templates are a great starting point, there are a number of customizations we wanted to make to our generated routes, including:

- Individual `export function` calls instead of a single export
- Flow types for parameters & return values
- Function names in camelCase
- I18n of route segments

Some of these _could_ be implemented as features in `js-routes-rails`, or provided as additional templates to choose from. However, there's no need to support every app-specific feature if the user can just build a template of their own based on the default ones.

I patched `RouteExporter` locally to allow for a custom path, and it made implementing all of our customizations a breeze.

## How?

I would suggest that we change the `template` option to use symbol names for the built-in templates, and interpret strings as custom paths.

```rb
Js::Routes::Rails.configure do |c|
  c.template = :commonjs
end
```

It's not a backwards compatible change though, so I wanted to hear your reaction before implementing anything.

There are of course other options in case we want to keep passing built-in template names as strings. We could check whether `template` looks like an absolute path, or whitelist included names, or something similar. However, I suspect that distinguishing between symbol-vs-string would be less prone to confusion than the alternatives.

Thoughts?

**Comment by damian** [comment]
@lime I absolutely agree that opening up the template to allow folk to transform the JS output in whatever way they need is a good idea and frees the burden up on me / this gem to solve every possible developer permutation.

In fact I think that if a configurable template as per your suggestion is implemented, I could deprecate and remove the commonjs one out of the box(I'm fairly sure it's not being used by anyone) and we can just fallback to the Rails one provided if a template is not set in the configuration object(it defaults to Rails already). Given that I'd be happy to release a new major version of this gem with said changes 👍 

If your still up for it a PR would be great! Lemme know how I can be of assistance if you need any 😎

**Comment by lime** [comment]
Great to hear! I'll see what I can do. :)

As for the `commonjs` template, I think there's merit to having more than one option available out of the box. It showcases the versatility of the templates, and provides a great starting point for customization. But we can follow up on that once we get custom templates working.
